name: Publish image to GitHub Package Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: machine-learning-apps/gpr-docker-publish@master
        with:
          IMAGE_NAME: 'docker-image'
          TAG: 'latest'
          DOCKERFILE_PATH: 'Dockerfile'
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_WRITE_TOKEN }}
